### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by kathleen-allyo** [bakwc/JamSpell#72] opened 2019-01-23 23:04 UTC
I've installed swig successfully but running into this issue when I run `pip3 install jamspell`

```
    creating build/temp.macosx-10.6-intel-3.6/contrib/phf
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -Ijamspell -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c jamspell/lang_model.cpp -o build/temp.macosx-10.6-intel-3.6/jamspell/lang_model.o -std=c++11 -O2
    In file included from jamspell/lang_model.cpp:9:
    jamspell/lang_model.hpp:3:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jp/2ys7q8bd2_vdfp63z9n60fvr0000gn/T/pip-build-h3s8gzs_/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/jp/2ys7q8bd2_vdfp63z9n60fvr0000gn/T/pip-i3zputth-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jp/2ys7q8bd2_vdfp63z9n60fvr0000gn/T/pip-build-h3s8gzs_/jamspell/
```

**Comment by ghunkins** [comment] 2019-04-16 21:34
I have this same issue. Mac (High Sierra) with Python 3.6.8.

**Comment by Raphencoder** [comment] 2019-08-26 13:45
Did you try here ?
Duplicate of #55

**Comment by bakwc** [comment] 2020-09-30 23:34
Fixed in master.

**Closed by bakwc** 2020-09-30 23:34 UTC
