### ISSUE TITLE
On MacOS: collate_byname failed to construct for en_US.utf-8

### ISSUE THREAD

**Issue by ebuildy** [bakwc/JamSpell#37] opened 2018-07-11 08:26 UTC
```
Python 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jamspell
>>> corrector = jamspell.TSpellCorrector()
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for en_US.utf-8
```

I see locale is hardcoded here => https://github.com/bakwc/JamSpell/blob/6ec521f4e55ad11d98c0d8c6fd381e0523de1e92/jamspell/utils.cpp#L35, why ?

**Comment by bakwc** [comment] 2018-07-11 18:30
It's a known bug, just have not fix it yet. You can try to remove hardocded locale yourself, I will be glad to accept your PR. Closing this issue, cause it's a duplicate of #17

**Closed by bakwc** 2018-07-11 18:30 UTC

**Comment by MrBenGriffin** [comment] 2019-01-10 13:22
Use "en_US.UTF-8"  mac os x uses upper case for UTF-8.
